version: "3.9"

services:
  deno:
    container_name: ww-backend
    image: deno
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
